#!/bin/bash
set -e

# will be 1 by default when run through github actions
CI=${CI:-0}

luacheck ./openwrt-openwisp-monitoring/ -a

# check scripts formatting
shellcheck \
  install-dev.sh \
  qa-format \
  run-qa-checks \
  runbuild \
  runtests \
  ./openwrt-openwisp-monitoring/files/monitoring.init \
  ./openwrt-openwisp-monitoring/files/monitoring.agent

if [ "$CI" -eq "1" ]; then
  shellcheck ./openwrt-openwisp-monitoring/files/monitoring.agent
  # copy files in github actions so that shell formatter can check for them
  cp openwrt-openwisp-monitoring/files/monitoring.init monitoring_init
else
  shfmt -d .
  shfmt -d openwrt-openwisp-monitoring/files/monitoring.init
fi

openwisp-qa-check \
  --skip-checkmigrations \
  --skip-isort \
  --skip-flake8 \
  --skip-black
